### ISSUE TITLE
Bootstrap loader add ~28 seconds to build time.

### ISSUE THREAD

**Issue by EnigmaticCode** [shakacode/bootstrap-loader#189]
Whenever I add in an import for bootstrap loader to my main entry point it adds ~28 seconds to the webpack build time.

> [11:09:28] Hash: 4ea07d70dc4958bd9bde
> Time: 30085ms

Let me know if I can provide any additional information.

**Comment by justin808** [comment]
Please try to publish a minimal reproduction case to a public repo on github.

**Comment by Daidalos117** [comment]
Have same problem! 
After using boostrap-loader, compiling is taking about 30s, before it took only 2-3s and I had scss imported with everything from bootstrap. Now I compile about half of scss bootstrap files but it takes much loonger :( for details se #224 . Can somebody please help ?
This is almost unusable for normal development.
Thanks

**Comment by Judahmeek** [comment]
@Daidalos117 I ran your repo here: https://ide.c9.io/judahmeek/myrepo and webpack consistently took between 6-8 seconds with Node 7.2 and Ubuntu 14.04.

@justin808 Bootstrap-loader does break use of [webpack's analyze tool](https://webpack.github.io/docs/build-performance.html#hints-from-build-stats) because its output doesn't conform to proper JSON when output through `webpack --profile --json > stats.json`. I'll investigate this issue further.

**Comment by Daidalos117** [comment]
I solved it. Seems that problem was old node version (3.3). Now it takes about 7s, so it's really better. Any tips how to better optimize it? Before boostrap-loader it took only 3s which was much nicer :) 
Thanks!
