### ISSUE TITLE
No PostCSS config

### ISSUE THREAD

**Issue by thepatrick** [shakacode/bootstrap-loader#239]
A fresh install fails today with the postcoss-loader unless I create `node_modules/bootstrap-loader/postcss.config.js` with the contents ```module.exports={};```

**Comment by killtheliterate** [comment]
Temporary fix that I've adopted follows.

*post-install.sh:*
```bash
#!/bin/bash

echo "module.exports = {}" >> node_modules/bootstrap-loader/postcss.config.js
```

*package.json:*
```json
{
  ...
  "scripts": {
    "postinstall": "./post-install.sh"
  }
}
```

**Comment by killtheliterate** [comment]
I don't think `bootstrap-loader` actually has much to do with `postcss`, since it's not a dependency. I am using `postcss-loader`, and while your fix works in a simple case, I get similar explosions about `postcss` in all my css directories. Weird 😢

**Comment by justin808** [comment]
@thepatrick, can you try #241.

I really have no idea why that file would fix the issue. If I can get an explanation, then I'd be happy to merge.

**Comment by justin808** [comment]
Please let me know what your findings out. I'm happy to consider a PR.

**Comment by killtheliterate** [comment]
So, not really sure where this issue belongs, but because folks have been talking about it here...

My build started working again when I moved my `postCSS` config out of `webpack.config` and into a `postcss.config.js`. @thepatrick are you also using that method to load `postcss` plugins?

**Comment by nicluo** [comment]
PostCSS config is loaded via [github.com/michael-ciniawsky/postcss-load-config](https://github.com/michael-ciniawsky/postcss-load-config). 25 days ago, an update made `postcss.config.js` mandatory by throwing the error rather than just logging in console. [Commit a6c32fd](https://github.com/michael-ciniawsky/postcss-load-config/commit/a6c32fd)

If you only use `postcss-loader` within `bootstrap-loader` (as part of the list of loaders in `.bootstraprc`), then `node_modules/bootstrap-loader/postcss.config.js` is all you need. If you use the loader in your own css, then you need a `postcss.config.js` in the project root as well.

**Comment by borysn** [comment]
@nicluo i am getting this as an issue, but i see it's over two months old, any update on this?

**Comment by borysn** [comment]
@nicluo nvm, i was confused about setting up postcss.config.js, but only adding `module.exports = {};` runs fine.

**Comment by giggio** [comment]
Just downgrade `postcss-loader` to `1.2.1` and add `postcss-load-config` version `1.0.0` to your package.json, and you are good to go, until they fix things on `bootstrap-loader`.

**Comment by killtheliterate** [comment]
@justin808 just reopened #241
