### ISSUE TITLE
webpack3 + ModuleConcatenationPlugin breaks styles

### ISSUE THREAD

**Issue by unsafecode** [shakacode/bootstrap-loader#308]
Upgrading to webpack@3.0.0 itself only made no changes, but including the new `ModuleConcatenationPlugin` to enable Scope Hoisting resulted in styles not being loaded.

**Comment by justin808** [comment]
@unsafecode can you help us troubleshoot this and create a PR to address the support for Webpack 3.0?

**Comment by vegas3416** [comment]
Is there any word on when Webpack3 will be supported? I'm running Webpack 3.3.0 and installed everything for Bootstrap 4 and am trying to do just a simple require('bootstrap-loader')  and it shot me an initial error that I needed to get bootstrap-sass  so I did and now I am getting this:  

RROR in ./node_modules/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.woff
Module parse failed: C:\Users\React\Dev-Production\node_modules\bootstrap-sass\assets\fonts\bootstrap\glyphicons-halflings
-regular.woff Unexpected character ' ' (1:4)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)

Can you guys provide any info on this?

**Comment by justin808** [comment]
@vegas3416 I'm backed up right now with other priorities. Can you help us with this? I'd love to get a PR merged and going for this! Let me know if you want a Slack invite to our ShakaCode room.

**Comment by unsafecode** [comment]
@justin808 have to find some time for that. Hopefully next week.

**Comment by vegas3416** [comment]
Don't worry about it. I ended up just importing the bootstrap into the html
instead of using the bootstrap loader to do it. Besides I'm using Webpack 3
and Bootstrap 4 and the documentation that is out there so far doesn't seem
to touch on the latest stuff just yet which is understandable since is
pretty new.

I'm fairly new to Webpack and more so using it with React otherwise I'd
tackle the Webpack stuff more but I just don't have time either as I'm
having to learning React for a work project and just need to get the
project moving forwards

**Comment by koolkt** [comment]
Im using webpack 3.5.4 and setting up the font loader like this: 
```
          {
              test: /\.(ttf|otf|eot|svg|woff(2)?)(\?[a-z0-9]+)?$/,
              loader: 'file-loader?name=fonts/[name].[ext]'
          },
```
 resolved the same issue
