### ISSUE TITLE
Error after adding

### ISSUE THREAD

**Issue by SergeyMell** [shakacode/bootstrap-loader#69]
After adding the bootstrap loader I get this error
```
ERROR in 
      For Node <= v0.12.x Babel polyfill is required.
      Make sure it's installed in your 'node_modules/' directory.
    
 @ ./~/bootstrap-loader/loader.js 1:0-44
```
I have node v 0.12.7
babel-polyfill exists in my node_modules

**Comment by justin808** [comment]
@SergeyMell We accepted some PRs related to this issue. We'll your help to debug this.

**Comment by SergeyMell** [comment]
What help can I provide?

**Comment by justin808** [comment]
@SergeyMell Please search the issues for the related issues on this topic and see help us debug what's missing. You can fork this repo and modify one of the examples in the `/examples` directory. At the minimum, create a reproducible case. Better yet, submit a PR with code or doc changes. 

Since this is a very old Node version, neither I nor @alexfedoseev will be spending time trying to support this. Nevertheless, we'll help you get your changes in.

Thanks!

**Comment by justin808** [comment]
@SergeyMell Any update?

**Comment by SergeyMell** [comment]
Because I had to make my project working as soon as possible, I've moved to Node 5.8.0 and the issue disappeared. Thus now it quite hard to create a project on the basis of Node v 0.12 but I will come up with some materials/propositions as soon as possible.
