### ISSUE TITLE
Bootstrap 4 NavBar style doesn't work properly

### ISSUE THREAD

**Issue by WellyShen** [shakacode/bootstrap-loader#71]
Hi, I use bs4 NavBar component, for example : 
`<nav class="navbar navbar-dark bg-inverse">
  
</nav>`

It seems not working properly.

**Comment by justin808** [comment]
I added this to the docs:

If you're using Bootstrap 4, you probably need:

npm install postcss-loader


see if that fixes the issue

if not, compare your set to the ones in the /examples directories.

**Comment by WellyShen** [comment]
Hi @justin808 ,

Thank you for your response, but I cloned your basic example and tried the bootstrap 4 "NavBar" on it. I seems not working properly.

**Comment by justin808** [comment]
fork the repo with this control in the example

then take a screen shot of the issue

better yet, help us debug why this is happening

until Bootstrap comes out of alpha, the core team is depending on the
community to debug these issues

thanks

**Comment by justin808** [comment]
@WellyShen Any update?

**Comment by petetan** [comment]
@justin808 @WellyShen I think there is some confusion due to the [basic .bootstraprc-4-example](https://github.com/shakacode/bootstrap-loader/blob/master/examples/basic/.bootstraprc-4-example) and [css-modules .bootstraprc-4-example](https://github.com/shakacode/bootstrap-loader/blob/master/examples/css-modules/.bootstraprc-4-example) files not being in sync with main  [.bootstraprc-4-default](https://github.com/shakacode/bootstrap-loader/blob/master/.bootstraprc-4-default).

Specifically 
```yml
utilities-background: true
``` 
from 13b544ad909db8a95005d0f01a1705b0d1cf7365.

**Comment by WellyShen** [comment]
Hi @petetan  @justin808 , Thank you for your support, I have tried it, now it works.
First, I add the following code into the ".bootstraprc-4-example" file
`utilities-background: true`
Then, tried bootstrap navbar inside the "bootstrap-dev.html" file
`<nav class="navbar navbar-dark bg-inverse">
  <a class="navbar-brand" href="#">Navbar</a>
  <ul class="nav navbar-nav">
     <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">About</a>
       </li>
  </ul>
</nav>`
