### ISSUE TITLE
Any reason why resolve.extensions is different from the default in the example webpack.config.js?

### ISSUE THREAD

**Issue by rjbergerud** [shakacode/bootstrap-loader#95]
Default is : `["", ".webpack.js", ".web.js", ".js"]`, while the webpack.config.js has `["", ".js"]`

**Comment by justin808** [comment]
@rjbergerud What file is that? I'm guessing that you are correct. Maybe create a PR?

**Comment by Judahmeek** [comment]
https://webpack.github.io/docs/configuration.html#resolve-extensions

Files are our examples' webpack.(dev || prod).config.js.

@rjbergerud My guess is that it's convention to restrict resolve extensions to extensions actually used in order to minimize the chance for file-name collisions. The other possibility, of course, is that the config files are based on a template. Can this issue be closed?
